/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author minhvuong
 */
public class ChiTietNV extends javax.swing.JPanel {

    /**
     * Creates new form ChiTietNV
     */
    public ChiTietNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 120, 217));
        jLabel1.setText("Mã Nhân Viên:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 120, 217));
        jLabel2.setText("Họ Tên:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 120, 217));
        jLabel3.setText("Giới Tính:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 120, 217));
        jLabel4.setText("SĐT:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 120, 217));
        jLabel5.setText("Địa Chỉ:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 120, 217));
        jLabel6.setText("Chức Vụ:");

        lblMa.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblMa.setForeground(new java.awt.Color(2, 120, 217));
        lblMa.setText("Họ Tên");

        lblNhanVien.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(2, 120, 217));
        lblNhanVien.setText("Họ Tên");

        lblGioiTinh.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(2, 120, 217));
        lblGioiTinh.setText("Họ Tên");

        lblSDT.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(2, 120, 217));
        lblSDT.setText("Họ Tên");

        lblDiaChi.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(2, 120, 217));
        lblDiaChi.setText("Họ Tên");

        lblChucVu.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(2, 120, 217));
        lblChucVu.setText("Họ Tên");

        lblNgaySinh.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(2, 120, 217));
        lblNgaySinh.setText("Họ Tên");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 120, 217));
        jLabel7.setText("Ngày Sinh:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 120, 217));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("THÔNG TIN NHÂN VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgaySinh)
                    .addComponent(lblChucVu)
                    .addComponent(lblDiaChi)
                    .addComponent(lblSDT)
                    .addComponent(lblGioiTinh)
                    .addComponent(lblNhanVien)
                    .addComponent(lblMa))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblChucVu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNhanVien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNgaySinh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblGioiTinh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSDT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDiaChi))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblChucVu;
    public javax.swing.JLabel lblDiaChi;
    public javax.swing.JLabel lblGioiTinh;
    public javax.swing.JLabel lblMa;
    public javax.swing.JLabel lblNgaySinh;
    public javax.swing.JLabel lblNhanVien;
    public javax.swing.JLabel lblSDT;
    // End of variables declaration//GEN-END:variables
}
